# Generated by Django 3.0.10 on 2020-10-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='dealer_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Chief_Administrator', 'Chief_Administrator'), ('Administrator', 'Administrator'), ('Dealer', 'Dealer'), ('User', 'User')], default='User', max_length=30, null=True, verbose_name='User role'),
        ),
    ]
