# Generated by Django 3.0.10 on 2020-10-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_group_create_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Administrator', 'Administrator'), ('Dealer', 'Dealer'), ('User', 'User')], default='User', max_length=30, null=True, verbose_name='User role'),
        ),
    ]
