# Generated by Django 3.0.10 on 2020-11-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201103_1314'),
        ('users', '0005_auto_20201103_1312'),
    ]

    operations = [
    ]
