# Generated by Django 3.0.10 on 2020-11-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201103_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dealer_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Dealer'),
        ),
    ]
