# Generated by Django 3.0.10 on 2020-11-04 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201103_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dealer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_users', to=settings.AUTH_USER_MODEL, verbose_name='Dealer'),
        ),
    ]
