# Generated by Django 3.0.10 on 2020-11-04 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201104_0713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='dealer_id',
            new_name='dealer',
        ),
    ]
