# Generated by Django 3.0.10 on 2020-11-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201104_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Administrator', 'Administrator'), ('Dealer', 'Dealer'), ('User', 'User')], max_length=30, null=True, verbose_name='User role'),
        ),
    ]
