# Generated by Django 3.0.10 on 2020-11-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201105_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Administrator', 'Administrator'), ('Dealer', 'Dealer'), ('Technical_Specialist', 'Technical_Specialist'), ('User', 'User')], max_length=30, null=True, verbose_name='User role'),
        ),
    ]
