# Generated by Django 3.0.10 on 2020-11-23 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20201123_1403'),
        ('users', '0014_auto_20201123_1205'),
    ]

    operations = [
    ]
