# Generated by Django 3.0.10 on 2020-11-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20201124_0911'),
        ('users', '0015_merge_20201123_1519'),
    ]

    operations = [
    ]
