# Generated by Django 3.0.10 on 2020-11-24 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20201123_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dealer',
            field=models.ForeignKey(help_text='Dealer who supplies user with stuff. Only for `User` role only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_users', to=settings.AUTH_USER_MODEL, verbose_name='Dealer'),
        ),
    ]
