# Generated by Django 3.0.10 on 2020-11-24 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_20201124_1258'),
        ('users', '0016_auto_20201124_1125'),
    ]

    operations = [
    ]
