# Generated by Django 3.0.10 on 2020-11-24 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('device', '0002_auto_20201124_1406'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='dealer',
            field=models.ForeignKey(blank=True, help_text='Dealer who supplies this labels pack.', limit_choices_to={'role': 'Dealer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Related Dealer'),
        ),
        migrations.AddField(
            model_name='label',
            name='linked_plotter',
            field=models.ForeignKey(blank=True, help_text='The plotter on which the film was activated by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_labels', to='device.Plotter', verbose_name='Linked plotters'),
        ),
        migrations.AddField(
            model_name='label',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who buy this pack of label.', limit_choices_to={'role': 'User'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_user', to=settings.AUTH_USER_MODEL, verbose_name='Related User'),
        ),
    ]
