# Generated by Django 3.0.10 on 2020-11-24 16:01

from django.db import migrations, models
import main_service_of_plotters.apps.materials.validators


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20201124_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='available_count',
            field=models.IntegerField(blank=True, default=0, help_text='Remaining labels in pack.', verbose_name='Available amount'),
        ),
        migrations.AlterField(
            model_name='label',
            name='barcode',
            field=models.CharField(help_text='Identification number of label/', max_length=16, unique=True, validators=[main_service_of_plotters.apps.materials.validators.validate_unique_code], verbose_name='Unique barcode'),
        ),
        migrations.AlterField(
            model_name='label',
            name='date_of_activation',
            field=models.DateTimeField(blank=True, default=None, help_text='Date then user activate this label in plotter.', null=True, verbose_name='Date of activation'),
        ),
        migrations.AlterField(
            model_name='label',
            name='scratch_code',
            field=models.CharField(help_text='Scratch code is secret key what user scratch from labels and put to system. Then system activate this label', max_length=16, unique=True, validators=[main_service_of_plotters.apps.materials.validators.validate_unique_code], verbose_name='Unique scratch code'),
        ),
    ]
