# Generated by Django 3.0.10 on 2020-10-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_auto_20201015_1442'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='label',
            name='scratch_code-barcode',
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together={('scratch_code', 'barcode')},
        ),
    ]
