# Generated by Django 3.0.10 on 2020-10-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_auto_20201015_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='count',
        ),
        migrations.RemoveField(
            model_name='label',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='label',
            name='date_life',
        ),
        migrations.RemoveField(
            model_name='label',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='label',
            name='size',
        ),
        migrations.RemoveField(
            model_name='label',
            name='template',
        ),
    ]
