# Generated by Django 3.0.10 on 2020-10-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0006_label_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
