# Generated by Django 3.0.10 on 2020-10-22 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0008_auto_20201022_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation'),
        ),
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(blank=True, choices=[('Phone', 'Phone'), ('Watch', 'Watch'), ('Camera', 'Camera')], max_length=60, verbose_name='category template'),
        ),
    ]
