# Generated by Django 3.0.10 on 2020-10-22 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0009_auto_20201022_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation'),
        ),
    ]
