# Generated by Django 3.0.10 on 2020-10-24 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('materials', '0010_auto_20201022_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='category',
        ),
        migrations.AddField(
            model_name='template',
            name='device_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.DeviceCategory', verbose_name='Name of template device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='file_photo',
            field=models.FileField(default=2, upload_to='', verbose_name='Upload file with photo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='file_plt',
            field=models.FileField(default=2, upload_to='', verbose_name='Upload file format .plt'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='manufacturer_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.Manufacturer', verbose_name='Name of template manufacturer'),
            preserve_default=False,
        ),
    ]
