# Generated by Django 3.0.10 on 2020-10-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0011_auto_20201024_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='date_update',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='date_update',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
