# Generated by Django 3.0.10 on 2020-10-24 12:59

from django.db import migrations, models
import django.db.models.deletion
import main_service_of_plotters.apps.materials.validators


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_modelstemplate'),
        ('materials', '0013_auto_20201024_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='model_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.ModelsTemplate', verbose_name='Name of template model'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='template',
            name='file_photo',
            field=models.FileField(upload_to='photo/%Y/%m/%d', validators=[main_service_of_plotters.apps.materials.validators.validate_file_photo], verbose_name='Upload file with photo'),
        ),
        migrations.AlterField(
            model_name='template',
            name='file_plt',
            field=models.FileField(upload_to='documents/%Y/%m/%d', validators=[main_service_of_plotters.apps.materials.validators.validate_file_plt], verbose_name='Upload file format .plt'),
        ),
    ]
