# Generated by Django 3.0.10 on 2020-10-24 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0014_auto_20201024_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='model_category',
        ),
    ]
