# Generated by Django 3.0.10 on 2020-10-24 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_modelstemplate'),
        ('materials', '0015_remove_template_model_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='model_category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='category.ModelsTemplate', verbose_name='Name of template model'),
            preserve_default=False,
        ),
    ]
