# Generated by Django 3.0.10 on 2020-10-26 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0016_template_model_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='dealer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Dealer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='instance model Dealer'),
        ),
        migrations.AddField(
            model_name='label',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'User'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_user', to=settings.AUTH_USER_MODEL, verbose_name='instance model User'),
        ),
    ]
