# Generated by Django 3.0.10 on 2020-11-02 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0011_auto_20201102_1114'),
        ('materials', '0018_label_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='date_of_activation',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='label',
            name='linked_plotter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_labels', to='device.Plotter'),
        ),
    ]
