# Generated by Django 3.0.10 on 2020-11-02 12:35

from django.db import migrations, models
import main_service_of_plotters.apps.materials.validators


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0018_label_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='barcode',
            field=models.CharField(blank=True, max_length=16, unique=True, validators=[main_service_of_plotters.apps.materials.validators.validate_unique_code], verbose_name='Unique barcode'),
        ),
        migrations.AlterField(
            model_name='label',
            name='scratch_code',
            field=models.CharField(blank=True, max_length=16, unique=True, validators=[main_service_of_plotters.apps.materials.validators.validate_unique_code], verbose_name='Unique scratch code'),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set(),
        ),
    ]
