# Generated by Django 3.0.10 on 2020-11-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0019_auto_20201102_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='available_count',
            field=models.IntegerField(default=0),
        ),
    ]
