# Generated by Django 3.0.10 on 2020-11-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0020_label_available_count'),
        ('materials', '0019_auto_20201102_1235'),
    ]

    operations = [
    ]
