# Generated by Django 3.0.10 on 2020-11-03 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_service_of_plotters.apps.materials.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0009_auto_20201103_0829'),
        ('device', '0012_auto_20201103_0829'),
        ('materials', '0021_merge_20201102_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='date_of_activation',
            field=models.DateTimeField(default=None, null=True, verbose_name='Date of activation'),
        ),
        migrations.AlterField(
            model_name='label',
            name='dealer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Dealer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Related Dealer'),
        ),
        migrations.AlterField(
            model_name='label',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='label',
            name='linked_plotter',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_labels', to='device.Plotter', verbose_name='Linked plotters'),
        ),
        migrations.AlterField(
            model_name='label',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'User'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_user', to=settings.AUTH_USER_MODEL, verbose_name='Related User'),
        ),
        migrations.AlterField(
            model_name='template',
            name='device_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.DeviceCategory', verbose_name='Category of devices'),
        ),
        migrations.AlterField(
            model_name='template',
            name='file_photo',
            field=models.FileField(upload_to='photo/%Y/%m/%d', validators=[main_service_of_plotters.apps.materials.validators.validate_file_photo], verbose_name='Schematic image of template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='file_plt',
            field=models.FileField(upload_to='documents/%Y/%m/%d', validators=[main_service_of_plotters.apps.materials.validators.validate_file_plt], verbose_name='Blueprint file (*.plt)'),
        ),
        migrations.AlterField(
            model_name='template',
            name='manufacturer_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Manufacturer', verbose_name='Manufacturer of the model'),
        ),
        migrations.AlterField(
            model_name='template',
            name='model_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.ModelsTemplate', verbose_name='Model of device'),
        ),
    ]
