# Generated by Django 3.0.10 on 2020-11-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0024_auto_20201103_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.AlterField(
            model_name='label',
            name='available_count',
            field=models.IntegerField(default=0, verbose_name='Available amount'),
        ),
        migrations.AlterField(
            model_name='label',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Start amount'),
        ),
    ]
