# Generated by Django 3.0.10 on 2020-11-03 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0025_auto_20201103_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
    ]
