# Generated by Django 3.0.10 on 2020-11-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0028_auto_20201103_1359'),
        ('materials', '0025_auto_20201103_1259'),
    ]

    operations = [
    ]
