# Generated by Django 3.0.10 on 2020-11-18 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0021_merge_20201118_1446'),
        ('materials', '0031_remove_label_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='linked_plotter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_labels', to='device.Plotter', verbose_name='Linked plotters'),
        ),
    ]
