# Generated by Django 3.0.10 on 2020-11-20 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main_service_of_plotters.apps.materials.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0024_merge_20201120_1555'),
        ('category', '0013_auto_20201120_1508'),
        ('materials', '0032_auto_20201118_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='available_count',
            field=models.IntegerField(default=0, help_text='Remaining labels in pack.', verbose_name='Available amount'),
        ),
        migrations.AlterField(
            model_name='label',
            name='barcode',
            field=models.CharField(blank=True, help_text='Identification number of label/', max_length=16, unique=True, validators=[main_service_of_plotters.apps.materials.validators.validate_unique_code], verbose_name='Unique barcode'),
        ),
        migrations.AlterField(
            model_name='label',
            name='count',
            field=models.IntegerField(default=0, help_text='Amount of labels in pack on the start', verbose_name='Start amount'),
        ),
        migrations.AlterField(
            model_name='label',
            name='date_of_activation',
            field=models.DateTimeField(default=None, help_text='Date then user activate this label in plotter.', null=True, verbose_name='Date of activation'),
        ),
        migrations.AlterField(
            model_name='label',
            name='dealer',
            field=models.ForeignKey(blank=True, help_text='Dealer who supplies this labels pack.', limit_choices_to={'role': 'Dealer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Related Dealer'),
        ),
        migrations.AlterField(
            model_name='label',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Show what label was activated early', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='label',
            name='linked_plotter',
            field=models.ForeignKey(blank=True, help_text='The plotter on which the film was activated by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_labels', to='device.Plotter', verbose_name='Linked plotters'),
        ),
        migrations.AlterField(
            model_name='label',
            name='scratch_code',
            field=models.CharField(blank=True, help_text='Scratch code is secret key what user scratch from labels and put to system. Then system activate this label', max_length=16, unique=True, validators=[main_service_of_plotters.apps.materials.validators.validate_unique_code], verbose_name='Unique scratch code'),
        ),
        migrations.AlterField(
            model_name='label',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who buy this pack of label.', limit_choices_to={'role': 'User'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='label_user', to=settings.AUTH_USER_MODEL, verbose_name='Related User'),
        ),
        migrations.AlterField(
            model_name='template',
            name='device_category',
            field=models.ForeignKey(blank=True, help_text='The type of device of template (phone, tablet, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.DeviceCategory', verbose_name='Category of devices'),
        ),
        migrations.AlterField(
            model_name='template',
            name='file_photo',
            field=models.FileField(help_text='File of schematic image of template', upload_to='photo/%Y/%m/%d', validators=[main_service_of_plotters.apps.materials.validators.validate_file_photo], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='template',
            name='manufacturer_category',
            field=models.ForeignKey(blank=True, help_text='Manufacturer of device of template (Apple, Samsung, etc.)', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Manufacturer', verbose_name='Manufacturer of the model'),
        ),
        migrations.AlterField(
            model_name='template',
            name='model_category',
            field=models.ForeignKey(blank=True, help_text='Name of device tempalte created for.', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.ModelsTemplate', verbose_name='Model of device'),
        ),
        migrations.AlterField(
            model_name='template',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Name of template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='size',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('S', 'S')], help_text='This is size, points to size of template', max_length=1, null=True, verbose_name='Size'),
        ),
    ]
