# Generated by Django 3.0.10 on 2020-11-24 14:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of update')),
                ('count', models.IntegerField(help_text='Count cut template on plotter', verbose_name='Count')),
                ('plotter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Plotter', verbose_name='Plotter serial number')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Template', verbose_name='Name of template')),
            ],
            options={
                'verbose_name': 'Template Statistic',
                'verbose_name_plural': 'Template Statistics',
            },
        ),
        migrations.CreateModel(
            name='StatisticsPlotter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of update')),
                ('ip', models.GenericIPAddressField(help_text='IP address plotter', verbose_name='IP')),
                ('last_request', models.DateField(default=django.utils.timezone.now, help_text='Last connection to server', verbose_name='Last connection')),
                ('count_cut', models.IntegerField(help_text='Count cut on plotter', verbose_name='Count cut')),
                ('plotter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Plotter', verbose_name='Plotter serial number')),
            ],
            options={
                'verbose_name': 'Plotter statistic',
                'verbose_name_plural': 'Plotter statistics',
            },
        ),
        migrations.CreateModel(
            name='CuttingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of update')),
                ('plotter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Plotter', verbose_name='Plotter')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Template', verbose_name='Name of template')),
            ],
            options={
                'verbose_name': 'Cutting Transaction',
                'verbose_name_plural': 'Cutting Transactions',
            },
        ),
    ]
