# Generated by Django 3.0.10 on 2020-10-22 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materials', '0008_auto_20201022_1328'),
        ('device', '0004_auto_20201022_1328'),
        ('statistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsplotter',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation'),
        ),
        migrations.AddField(
            model_name='statisticsplotter',
            name='date_update',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='statisticstemplate',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation'),
        ),
        migrations.AddField(
            model_name='statisticstemplate',
            name='date_update',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='CuttingTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation')),
                ('date_update', models.DateTimeField(default=None, null=True)),
                ('date_cutted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation cut')),
                ('label_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.Label', verbose_name='instance model user')),
                ('plotter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Plotter', verbose_name='instance model plotter')),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Template', verbose_name='instance model user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='instance model user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
