# Generated by Django 3.0.10 on 2020-10-22 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0004_auto_20201022_1328'),
        ('materials', '0010_auto_20201022_1439'),
        ('statistics', '0002_auto_20201022_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='statisticsplotter',
            name='plotter_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.Plotter', verbose_name='instance model plotter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuttingtransaction',
            name='label_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materials.Label', verbose_name='instance model label'),
        ),
    ]
