# Generated by Django 3.0.10 on 2020-10-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0003_auto_20201022_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuttingtransaction',
            old_name='label_id',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='cuttingtransaction',
            old_name='plotter_id',
            new_name='plotter',
        ),
        migrations.RenameField(
            model_name='cuttingtransaction',
            old_name='template_id',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='cuttingtransaction',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='statisticsplotter',
            old_name='IP',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='statisticsplotter',
            old_name='plotter_id',
            new_name='plotter',
        ),
        migrations.RenameField(
            model_name='statisticstemplate',
            old_name='plotter_id',
            new_name='plotter',
        ),
        migrations.RenameField(
            model_name='statisticstemplate',
            old_name='template_id',
            new_name='template',
        ),
        migrations.AlterField(
            model_name='cuttingtransaction',
            name='date_update',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='statisticsplotter',
            name='date_update',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='statisticstemplate',
            name='date_update',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
