# Generated by Django 3.0.10 on 2020-10-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0016_template_model_category'),
        ('statistics', '0005_auto_20201024_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingtransaction',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Template', verbose_name='instance model template'),
        ),
    ]
