# Generated by Django 3.0.10 on 2020-10-30 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0006_auto_20201025_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingtransaction',
            name='label',
        ),
        migrations.AlterField(
            model_name='statisticsplotter',
            name='last_request',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='last connection to server'),
        ),
    ]
