# Generated by Django 3.0.10 on 2020-11-03 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0012_auto_20201103_0829'),
        ('materials', '0022_auto_20201103_0829'),
        ('statistics', '0007_auto_20201030_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingtransaction',
            name='plotter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Plotter', verbose_name='Plotter serial number'),
        ),
        migrations.AlterField(
            model_name='cuttingtransaction',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Template', verbose_name='Name of template'),
        ),
        migrations.AlterField(
            model_name='cuttingtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='statisticsplotter',
            name='last_request',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Last connection to server'),
        ),
        migrations.AlterField(
            model_name='statisticsplotter',
            name='plotter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Plotter', verbose_name='Plotter serial number'),
        ),
        migrations.AlterField(
            model_name='statisticstemplate',
            name='plotter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Plotter', verbose_name='Plotter serial number'),
        ),
        migrations.AlterField(
            model_name='statisticstemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.Template', verbose_name='Name of template'),
        ),
    ]
