# Generated by Django 3.0.10 on 2020-11-03 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0009_auto_20201103_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingtransaction',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date of update'),
        ),
        migrations.AlterField(
            model_name='statisticsplotter',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date of update'),
        ),
        migrations.AlterField(
            model_name='statisticstemplate',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date of update'),
        ),
    ]
