# Generated by Django 3.0.10 on 2020-11-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0009_auto_20201103_1259'),
        ('statistics', '0010_auto_20201103_1351'),
    ]

    operations = [
    ]
