# Generated by Django 3.0.10 on 2020-11-20 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0011_merge_20201103_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsplotter',
            name='count_cut',
            field=models.IntegerField(help_text='Count cut ', verbose_name='Count cut'),
        ),
        migrations.AlterField(
            model_name='statisticsplotter',
            name='ip',
            field=models.CharField(help_text='IP address plotter', max_length=150, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='statisticsplotter',
            name='last_request',
            field=models.DateField(default=django.utils.timezone.now, help_text='Last connection to server', verbose_name='Last connection'),
        ),
    ]
