# Generated by Django 3.0.10 on 2020-11-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0012_auto_20201120_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsplotter',
            name='ip',
            field=models.GenericIPAddressField(help_text='IP address plotter', verbose_name='IP'),
        ),
    ]
