# Generated by Django 3.0.10 on 2020-11-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics', '0014_auto_20201120_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuttingtransaction',
            name='date_cutted',
        ),
    ]
