# Generated by Django 3.0.10 on 2020-11-24 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plotter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of update')),
                ('serial_number', models.CharField(help_text='Serial number of plotter (typically printed on label)', max_length=16, unique=True, verbose_name='Serial number')),
            ],
            options={
                'verbose_name': 'Plotter',
                'verbose_name_plural': 'Plotters',
            },
        ),
    ]
