# Generated by Django 3.0.10 on 2020-11-24 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='dealer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Dealer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Dealer'),
        ),
        migrations.AddField(
            model_name='plotter',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'User'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plotter_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
