# Generated by Django 3.0.10 on 2020-10-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_plotter_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='serial_number',
            field=models.BigIntegerField(),
        ),
    ]
