# Generated by Django 3.0.10 on 2020-10-22 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0003_auto_20201019_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='date_creation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation'),
        ),
        migrations.AddField(
            model_name='plotter',
            name='date_update',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
