# Generated by Django 3.0.10 on 2020-10-26 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0006_auto_20201024_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'Dealer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='instance model User'),
        ),
    ]
