# Generated by Django 3.0.10 on 2020-10-26 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0007_auto_20201026_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='dealer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Dealer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='instance model Dealer'),
        ),
        migrations.AlterField(
            model_name='plotter',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'user'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_user', to=settings.AUTH_USER_MODEL, verbose_name='instance model User'),
        ),
    ]
