# Generated by Django 3.0.10 on 2020-10-26 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('device', '0008_auto_20201026_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='user',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'User'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plotter_user', to=settings.AUTH_USER_MODEL, verbose_name='instance model User'),
        ),
    ]
