# Generated by Django 3.0.10 on 2020-10-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0009_auto_20201026_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='available_film',
            field=models.IntegerField(default=0),
        ),
    ]
