# Generated by Django 3.0.10 on 2020-11-10 14:05

from django.db import migrations, models
import main_service_of_plotters.apps.device.models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_plotter_available_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotter',
            name='device_id',
            field=models.CharField(default=main_service_of_plotters.apps.device.models.random_string, max_length=15),
        ),
    ]
