# Generated by Django 3.0.10 on 2020-11-02 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0010_plotter_available_film'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='available_film',
            field=models.BigIntegerField(),
        ),
    ]
