# Generated by Django 3.0.10 on 2020-11-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_auto_20201103_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='serial_number',
            field=models.BigIntegerField(verbose_name='Serial number'),
        ),
    ]
