# Generated by Django 3.0.10 on 2020-11-18 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_auto_20201110_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='serial_number',
            field=models.CharField(help_text='Serial numbuer of plotter (typicaly printed on label', max_length=16, unique=True, verbose_name='Serial number'),
        ),
    ]
