# Generated by Django 3.0.10 on 2020-11-19 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0014_auto_20201118_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotter',
            name='device_id',
        ),
    ]
