# Generated by Django 3.0.10 on 2020-11-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0016_merge_20201103_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='available_film',
            field=models.BigIntegerField(verbose_name='Available film'),
        ),
    ]
