# Generated by Django 3.0.10 on 2020-11-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0017_auto_20201103_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='available_film',
            field=models.BigIntegerField(default=0, verbose_name='Available film'),
        ),
    ]
