# Generated by Django 3.0.10 on 2020-11-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0018_auto_20201103_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plotter',
            name='available_film',
        ),
    ]
