# Generated by Django 3.0.10 on 2020-11-16 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0012_auto_20201110_1406'),
        ('device', '0019_remove_plotter_available_film'),
    ]

    operations = [
    ]
