# Generated by Django 3.0.10 on 2020-11-18 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0020_merge_20201116_1507'),
        ('device', '0014_auto_20201118_0754'),
    ]

    operations = [
    ]
