# Generated by Django 3.0.10 on 2020-11-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0021_merge_20201118_1446'),
        ('device', '0015_remove_plotter_device_id'),
    ]

    operations = [
    ]
