# Generated by Django 3.0.10 on 2020-11-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0022_merge_20201120_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plotter',
            name='serial_number',
            field=models.CharField(help_text='Serial number of plotter (typically printed on label)', max_length=16, unique=True, verbose_name='Serial number'),
        ),
    ]
