# Generated by Django 3.0.10 on 2020-11-20 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0022_merge_20201120_1526'),
        ('device', '0023_auto_20201120_1508'),
    ]

    operations = [
    ]
