version: '3.2'

services:
  django_devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # [Choice] Python version: 3, 3.8, 3.7, 3.6
        VARIANT: 3
        # [Choice] Install Node.js
        # INSTALL_NODE: "true"
        # NODE_VERSION: "lts/*"
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
      cache_from:
        - main_service_of_plotters_devcontainer_django
    image: main_service_of_plotters_devcontainer_django
    container_name: django_devcontainer
    volumes:
      - ..:/app:z
    env_file:
      - ../.envs/.local/.django
      - ../.envs/.local/.postgres
    environment:
      - POSTGRES_HOST=postgres_devcontainer

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:postgres_devcontainer

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  postgres_devcontainer:
    build:
      context: ..
      dockerfile: ./compose/production/postgres/Dockerfile
    restart: unless-stopped
    image: main_service_of_plotters_devcontainer_postgres
    container_name: postgres_devcontainer
    volumes:
      - local_main_service_postgres_devcontainer_data:/var/lib/postgresql/data:Z
      - local_main_service_postgres_devcontainer_data_backups:/backups:z
    env_file:
      - ../.envs/.local/.postgres
    environment:
      - POSTGRES_HOST=postgres_devcontainer


    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  local_main_service_postgres_devcontainer_data: {}
  local_main_service_postgres_devcontainer_data_backups: {}
