# Generated by Django 3.0.10 on 2020-10-24 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation')),
                ('date_update', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Name of template device')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation')),
                ('date_update', models.DateTimeField(default=None, null=True)),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Name of template manufacturer')),
                ('device_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.DeviceCategory', verbose_name='Instance model device')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
