# Generated by Django 3.0.10 on 2020-10-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategory',
            name='date_update',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='date_update',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
