# Generated by Django 3.0.10 on 2020-10-24 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20201024_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelsTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation')),
                ('date_update', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Name of model template')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Manufacturer', verbose_name='Instance model manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
