# Generated by Django 3.0.10 on 2020-10-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_modelstemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicecategory',
            name='photo',
            field=models.ImageField(default=0, upload_to='device/%Y/%m/%d', verbose_name='Photo Device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='photo',
            field=models.ImageField(default=0, upload_to='manufacturer/%Y/%m/%d', verbose_name='Photo manufacturer'),
            preserve_default=False,
        ),
    ]
