# Generated by Django 3.0.10 on 2020-10-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20201025_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategory',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='device/%Y/%m/%d', verbose_name='Photo Device'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='manufacturer/%Y/%m/%d', verbose_name='Photo manufacturer'),
        ),
    ]
