# Generated by Django 3.0.10 on 2020-10-30 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_auto_20201025_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='device_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='category.DeviceCategory', verbose_name='Instance model device'),
        ),
    ]
