# Generated by Django 3.0.10 on 2020-10-30 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20201030_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelstemplate',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelstemplate', to='category.Manufacturer', verbose_name='Instance model manufacturer'),
        ),
    ]
