# Generated by Django 3.0.10 on 2020-11-03 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20201030_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategory',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name of category of devices'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='device_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='category.DeviceCategory', verbose_name='Category of devices'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name of manufacturer'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='manufacturer/%Y/%m/%d', verbose_name='Manufacturer image'),
        ),
        migrations.AlterField(
            model_name='modelstemplate',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelstemplate', to='category.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='modelstemplate',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Name of model'),
        ),
    ]
