# Generated by Django 3.0.10 on 2020-11-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20201103_0829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicecategory',
            options={'verbose_name': 'Device category', 'verbose_name_plural': 'Device categories'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='modelstemplate',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Models'},
        ),
    ]
