# Generated by Django 3.0.10 on 2020-11-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20201103_1351'),
        ('category', '0010_auto_20201103_1259'),
    ]

    operations = [
    ]
