# Generated by Django 3.0.10 on 2020-11-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_merge_20201103_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicecategory',
            name='name',
            field=models.CharField(blank=True, help_text='Name of category of devices', max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='devicecategory',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of category of devices', null=True, upload_to='device/%Y/%m/%d', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(blank=True, help_text='Name of manufacturer', max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='photo',
            field=models.ImageField(blank=True, help_text='Photo of manufacturer', null=True, upload_to='manufacturer/%Y/%m/%d', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='modelstemplate',
            name='name',
            field=models.CharField(blank=True, help_text='Name of models template', max_length=150, verbose_name='Name'),
        ),
    ]
