# Generated by Django 3.0.10 on 2020-11-05 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0019_remove_plotter_available_film'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Short name of porblem, will be displaied', max_length=100, verbose_name='Name')),
                ('populated_header', models.CharField(help_text='Text what will be populated in created ticket header', max_length=50, verbose_name='Populated Header')),
                ('populated_text', models.TextField(help_text='Text what will be populated in created ticket text', verbose_name='Populated Text')),
            ],
            options={
                'verbose_name': 'Popular problem',
                'verbose_name_plural': 'Popular problems',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of update')),
                ('header', models.CharField(help_text='Short description of problem.', max_length=50, verbose_name='Header')),
                ('text', models.TextField(blank=True, help_text='Description of problem', verbose_name='Text')),
                ('media_file', models.FileField(null=True, upload_to='ticket_media/', verbose_name='Attached media file')),
                ('status', models.CharField(choices=[('O', 'Open'), ('W', 'In Work'), ('S', 'Solved'), ('C', 'Closed')], default='O', max_length=1, verbose_name='Status')),
                ('assignee', models.ForeignKey(default=None, help_text='Technical Specialist who manage ticket', limit_choices_to={'is_technical_specialist': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assignee')),
                ('plotter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='device.Plotter', verbose_name='Plotter')),
                ('reporter', models.ForeignKey(help_text='User who create ticket', limit_choices_to={'is_user': True}, on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Repoeter')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
            },
        ),
    ]
