# Generated by Django 3.0.10 on 2020-11-24 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopularProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Short name of problem, will be displayed', max_length=100, verbose_name='Name')),
                ('populated_header', models.CharField(help_text='Text what will be populated in created ticket header', max_length=50, verbose_name='Populated Header')),
                ('populated_text', models.TextField(blank=True, help_text='Text what will be populated in created ticket text', verbose_name='Populated Text')),
            ],
            options={
                'verbose_name': 'Popular problem',
                'verbose_name_plural': 'Popular problems',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data of creation')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Date of update')),
                ('header', models.CharField(help_text='Short description of problem.', max_length=50, verbose_name='Header')),
                ('text', models.TextField(blank=True, help_text='Description of problem', verbose_name='Text')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='ticket_media/', verbose_name='Attached media file')),
                ('status', models.CharField(choices=[('O', 'Open'), ('W', 'In Work'), ('S', 'Solved'), ('C', 'Closed')], default='O', max_length=1, verbose_name='Status')),
                ('answer', models.TextField(blank=True, help_text='Answer of assigned technical specialist', verbose_name='Answer')),
                ('answer_attached_file', models.FileField(blank=True, help_text='Media file attached by assigned technical specialist', null=True, upload_to='ticket_media/', verbose_name='Answer media file')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'permissions': [('can_report_problem', 'Can report a problem'), ('can_close_ticket', 'Can change ticket status to Close'), ('can_solve_problems', "Can solve ticket's problems")],
            },
        ),
    ]
