# Generated by Django 3.0.10 on 2020-11-24 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket', '0001_initial'),
        ('device', '0002_auto_20201124_1406'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assignee',
            field=models.ForeignKey(blank=True, help_text='Technical Specialist who manage ticket', limit_choices_to={'role': 'Technical_Specialist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assignee'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='plotters',
            field=models.ManyToManyField(related_name='tickets', to='device.Plotter', verbose_name='Plotters'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reporter',
            field=models.ForeignKey(help_text='User who create ticket', limit_choices_to={'role': 'User'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Reporter'),
        ),
    ]
