# Generated by Django 3.0.10 on 2020-11-05 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0019_remove_plotter_available_film'),
        ('ticket', '0003_auto_20201105_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='plotter',
        ),
        migrations.AddField(
            model_name='ticket',
            name='plotters',
            field=models.ManyToManyField(related_name='tickets', to='device.Plotter', verbose_name='Plotters'),
        ),
    ]
