# Generated by Django 3.0.10 on 2020-11-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20201105_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answer',
            field=models.TextField(blank=True, help_text='Answer of assigned technical specialist', verbose_name='Answer'),
        ),
    ]
