# Generated by Django 3.0.10 on 2020-11-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticket_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='answer_attached_file',
            field=models.FileField(blank=True, help_text='Media file attached by assigned technical specailist', null=True, upload_to='ticket_media/', verbose_name='Answer media file'),
        ),
    ]
