# Generated by Django 3.0.10 on 2020-11-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20201109_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'permissions': [('can_report_problem', 'Can report a problem'), ('can_close_ticket', 'Can change ticket status to Close'), ('can_solve_problems', "Can solve ticket's problems")], 'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
